language: java

## https://github.com/travis-ci/travis-ci/issues/3259
sudo: required
install: true

## maven-invoker-plugin is called after deploying javafx-maven-plugin into local repository, so change default-test-call to "install" (because its called at that maven-phase)

script:
  - sudo apt-get update && sudo apt-get install oracle-java8-installer
  - java -version
  - mvn install -B

jdk:
  - oraclejdk8

branches:
  only:
  - master
  
notifications:
  email: false
